// "use client";

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { SessionProvider } from "next-auth/react"
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'

const inter = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Coursewave',
  description: 'Generated by create next app',
  icons: {
    icon: "/courseWaveFaviconColored.ico",
    shortcut: "/courseWaveFaviconColored.ico",
  },
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: { session: any, expires: string }
}) {
  return (
    <ClerkProvider>
    <html lang="en">
        <body className={cn(
          "!scroll-smooth",
          inter.className
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider></body>
    </html>
  </ClerkProvider>

  )
}
