"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ToastProvider } from "@/components/providers/toaster-provider";
import { useRouter } from "next/navigation";
import LandingPageHeader from "@/components/LandingPage/header";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Coursewave",
  description: "Generated by create next app",
  icons: {
    icon: "/courseWaveFaviconColored.ico",
    shortcut: "/courseWaveFaviconColored.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  const handleLoginClick = () => {
    router.push("/login");
  };

  const handleSignUpClick = () => {
    router.push("/register");
  };

  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <Provider store={store}> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastProvider />

          {/* <Provider store={store}> */}
          <div className="dark:bg-black">
            <LandingPageHeader handleLoginClick={handleLoginClick} />
            {children}
          </div>
        </ThemeProvider>

        {/* </Provider> */}
      </body>
    </html>
  );
}
