import './globals.css'
import { store } from './store'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'

const poppins = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Coursewave',
  description: 'Generated by create next app',
  icons: {
    icon: "/courseWaveFaviconColored.ico",
    shortcut: "/courseWaveFaviconColored.ico",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <Provider store={store}> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}

          </ThemeProvider>

        {/* </Provider> */}

      </body>
    </html>
  )
}