import { MarkerType } from "reactflow";

export const roadmapTemplates = {
  "backend developer": {
    title: "Backend Developer Roadmap",
    description: "Master server-side development, databases, and API design",
    duration: "6-12 months",
    difficulty: "Intermediate",
    category: "Development",
    nodes: [
      {
        id: "1",
        type: "custom",
        position: { x: 0, y: 0 },
        data: {
          label: "Programming Fundamentals",
          description: "Choose a language: Node.js, Python, Java, Go, or C#",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "2",
        type: "custom",
        position: { x: 0, y: 150 },
        data: {
          label: "Web Fundamentals",
          description: "HTTP, REST APIs, JSON, Web Security basics",
          type: "foundation",
          estimatedTime: "1-2 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "3",
        type: "custom",
        position: { x: 250, y: 75 },
        data: {
          label: "Database Design",
          description: "SQL, NoSQL, Database modeling and optimization",
          type: "intermediate",
          estimatedTime: "2-3 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "4",
        type: "custom",
        position: { x: 250, y: 225 },
        data: {
          label: "API Development",
          description: "RESTful APIs, GraphQL, API documentation",
          type: "intermediate",
          estimatedTime: "2-3 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "5",
        type: "custom",
        position: { x: 500, y: 150 },
        data: {
          label: "Authentication & Security",
          description: "JWT, OAuth, Password hashing, CORS, Rate limiting",
          type: "advanced",
          estimatedTime: "1-2 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "6",
        type: "custom",
        position: { x: 500, y: 300 },
        data: {
          label: "Testing & Deployment",
          description: "Unit testing, Integration testing, CI/CD, Docker",
          type: "advanced",
          estimatedTime: "2-3 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "7",
        type: "custom",
        position: { x: 750, y: 225 },
        data: {
          label: "Microservices & Cloud",
          description: "Microservices architecture, AWS/Azure/GCP, Kubernetes",
          type: "expert",
          estimatedTime: "3-4 months",
          difficulty: "Expert",
        },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e1-3",
        source: "1",
        target: "3",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-4",
        source: "2",
        target: "4",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e4-6",
        source: "4",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e5-7",
        source: "5",
        target: "7",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e6-7",
        source: "6",
        target: "7",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
    ],
  },
  "frontend developer": {
    title: "Frontend Developer Roadmap",
    description: "Master modern web development with React, Vue, or Angular",
    duration: "6-10 months",
    difficulty: "Intermediate",
    category: "Development",
    nodes: [
      {
        id: "1",
        type: "custom",
        position: { x: 0, y: 0 },
        data: {
          label: "HTML & CSS",
          description: "Semantic HTML, CSS Grid, Flexbox, Responsive Design",
          type: "foundation",
          estimatedTime: "1-2 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "2",
        type: "custom",
        position: { x: 0, y: 150 },
        data: {
          label: "JavaScript Fundamentals",
          description: "ES6+, DOM manipulation, Async programming",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "3",
        type: "custom",
        position: { x: 250, y: 75 },
        data: {
          label: "React/Vue/Angular",
          description: "Choose a framework and master its ecosystem",
          type: "intermediate",
          estimatedTime: "3-4 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "4",
        type: "custom",
        position: { x: 250, y: 225 },
        data: {
          label: "State Management",
          description: "Redux, Context API, Vuex, NgRx",
          type: "intermediate",
          estimatedTime: "1-2 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "5",
        type: "custom",
        position: { x: 500, y: 150 },
        data: {
          label: "Testing & Performance",
          description: "Jest, React Testing Library, Performance optimization",
          type: "advanced",
          estimatedTime: "2-3 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "6",
        type: "custom",
        position: { x: 500, y: 300 },
        data: {
          label: "Build Tools & Deployment",
          description: "Webpack, Vite, CI/CD, Vercel/Netlify",
          type: "advanced",
          estimatedTime: "1-2 months",
          difficulty: "Advanced",
        },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e4-6",
        source: "4",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e5-6",
        source: "5",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
    ],
  },
  "data scientist": {
    title: "Data Scientist Roadmap",
    description:
      "Master data analysis, machine learning, and statistical modeling",
    duration: "8-12 months",
    difficulty: "Advanced",
    category: "Data Science",
    nodes: [
      {
        id: "1",
        type: "custom",
        position: { x: 0, y: 0 },
        data: {
          label: "Python & Statistics",
          description: "Python programming, Statistical concepts, Probability",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "2",
        type: "custom",
        position: { x: 0, y: 150 },
        data: {
          label: "Data Manipulation",
          description: "Pandas, NumPy, Data cleaning and preprocessing",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "3",
        type: "custom",
        position: { x: 250, y: 75 },
        data: {
          label: "Data Visualization",
          description: "Matplotlib, Seaborn, Plotly, Storytelling with data",
          type: "intermediate",
          estimatedTime: "1-2 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "4",
        type: "custom",
        position: { x: 250, y: 225 },
        data: {
          label: "Machine Learning",
          description: "Scikit-learn, Supervised/Unsupervised learning",
          type: "intermediate",
          estimatedTime: "3-4 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "5",
        type: "custom",
        position: { x: 500, y: 150 },
        data: {
          label: "Deep Learning",
          description: "TensorFlow/PyTorch, Neural networks, Computer vision",
          type: "advanced",
          estimatedTime: "3-4 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "6",
        type: "custom",
        position: { x: 500, y: 300 },
        data: {
          label: "MLOps & Deployment",
          description: "Model deployment, MLflow, Kubeflow, Cloud platforms",
          type: "expert",
          estimatedTime: "2-3 months",
          difficulty: "Expert",
        },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-4",
        source: "2",
        target: "4",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e5-6",
        source: "5",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
    ],
  },
  "devops engineer": {
    title: "DevOps Engineer Roadmap",
    description: "Master infrastructure automation, CI/CD, and cloud platforms",
    duration: "6-10 months",
    difficulty: "Advanced",
    category: "Operations",
    nodes: [
      {
        id: "1",
        type: "custom",
        position: { x: 0, y: 0 },
        data: {
          label: "Linux & Networking",
          description:
            "Linux administration, Networking fundamentals, Shell scripting",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "2",
        type: "custom",
        position: { x: 0, y: 150 },
        data: {
          label: "Cloud Platforms",
          description: "AWS, Azure, or GCP fundamentals and services",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "3",
        type: "custom",
        position: { x: 250, y: 75 },
        data: {
          label: "Containerization",
          description: "Docker, Container orchestration basics",
          type: "intermediate",
          estimatedTime: "1-2 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "4",
        type: "custom",
        position: { x: 250, y: 225 },
        data: {
          label: "CI/CD Pipelines",
          description:
            "Jenkins, GitLab CI, GitHub Actions, Pipeline automation",
          type: "intermediate",
          estimatedTime: "2-3 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "5",
        type: "custom",
        position: { x: 500, y: 150 },
        data: {
          label: "Kubernetes",
          description: "Container orchestration, K8s administration, Helm",
          type: "advanced",
          estimatedTime: "3-4 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "6",
        type: "custom",
        position: { x: 500, y: 300 },
        data: {
          label: "Monitoring & Security",
          description:
            "Prometheus, Grafana, Security best practices, Compliance",
          type: "expert",
          estimatedTime: "2-3 months",
          difficulty: "Expert",
        },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-4",
        source: "2",
        target: "4",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e5-6",
        source: "5",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
    ],
  },
  "mobile developer": {
    title: "Mobile Developer Roadmap",
    description: "Master iOS and Android development with modern frameworks",
    duration: "6-10 months",
    difficulty: "Intermediate",
    category: "Mobile",
    nodes: [
      {
        id: "1",
        type: "custom",
        position: { x: 0, y: 0 },
        data: {
          label: "Programming Fundamentals",
          description: "Swift (iOS) or Kotlin/Java (Android), OOP concepts",
          type: "foundation",
          estimatedTime: "2-3 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "2",
        type: "custom",
        position: { x: 0, y: 150 },
        data: {
          label: "UI/UX Design",
          description:
            "Mobile design principles, Material Design, Human Interface Guidelines",
          type: "foundation",
          estimatedTime: "1-2 months",
          difficulty: "Beginner",
        },
      },
      {
        id: "3",
        type: "custom",
        position: { x: 250, y: 75 },
        data: {
          label: "Native Development",
          description: "iOS (SwiftUI/UIKit) or Android (Jetpack Compose/Views)",
          type: "intermediate",
          estimatedTime: "3-4 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "4",
        type: "custom",
        position: { x: 250, y: 225 },
        data: {
          label: "Cross-Platform",
          description:
            "React Native, Flutter, or Xamarin for multi-platform apps",
          type: "intermediate",
          estimatedTime: "2-3 months",
          difficulty: "Intermediate",
        },
      },
      {
        id: "5",
        type: "custom",
        position: { x: 500, y: 150 },
        data: {
          label: "Testing & Performance",
          description:
            "Unit testing, UI testing, Performance optimization, Memory management",
          type: "advanced",
          estimatedTime: "2-3 months",
          difficulty: "Advanced",
        },
      },
      {
        id: "6",
        type: "custom",
        position: { x: 500, y: 300 },
        data: {
          label: "App Store & Deployment",
          description:
            "App Store Connect, Google Play Console, CI/CD for mobile",
          type: "advanced",
          estimatedTime: "1-2 months",
          difficulty: "Advanced",
        },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e2-4",
        source: "2",
        target: "4",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
      {
        id: "e5-6",
        source: "5",
        target: "6",
        markerEnd: { type: MarkerType.ArrowClosed },
      },
    ],
  },
};
